Console.WriteLine("Cidades do Litoral Sul de São Paulo");
Console.WriteLine();
Console.WriteLine("Cananéia");
Console.WriteLine("Ilha Comprida");
Console.WriteLine("Iguape");
Console.WriteLine("Peruíbe");
Console.WriteLine("Itanhaém");
Console.WriteLine("Mongaguá");
Console.WriteLine("Praia Grande");
Console.WriteLine("São Vicente");
Console.WriteLine("Santos");
Console.WriteLine("GUarujá");
Console.WriteLine("Bertioga");
Console.WriteLine("São Sebastião");
Console.WriteLine("Ihabela");
Console.WriteLine("Caraguatatuba");
Console.WriteLine("Ubatuba");